sudo: required
language: java
jdk:
  - oraclejdk8
before_install:
  - .travis/oracle/download.sh
  - .travis/oracle/install.sh  
before_script:
  - .travis/database.sh
after_success:
  - mvn clean cobertura:cobertura coveralls:report
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - clang
